# Generated by Django 5.1.2 on 2024-11-11 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('tipoMovie', models.CharField(choices=[('Serie', 'Serie')], max_length=20)),
                ('directores', models.ManyToManyField(to='movies.director')),
            ],
        ),
    ]
