# Generated by Django 5.1.2 on 2024-11-28 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='tipoMovie',
            field=models.CharField(choices=[('Pelicula', 'Pelicula'), ('Serie', 'Serie')], max_length=20),
        ),
    ]
