# Generated by Django 5.1.2 on 2024-11-28 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_usuario_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usuario',
            new_name='User',
        ),
    ]
