# Generated by Django 5.1.2 on 2024-12-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_remove_user_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='directores',
            field=models.ManyToManyField(blank=True, null=True, to='movies.director'),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=200)),
                ('correo', models.EmailField(max_length=200)),
                ('fecha', models.DateField()),
                ('comentarios', models.CharField(max_length=500)),
                ('peliculas', models.ManyToManyField(blank=True, null=True, to='movies.movie')),
            ],
        ),
    ]
